# Common configuration.

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - '**/db/migrate/*'
    - '**/db/schema.rb'
    - '**/Gemfile.lock'
    - '**/Rakefile'
    - '**/rails'
    - '**/vendor/**/*'
    - '**/spec_helper.rb'
    - 'node_modules/**/*'
    - 'bin/*'

## Layout

Layout/LineLength:
  Max: 160

## Metrics

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - '**/*_spec.rb'

Metrics/MethodLength:
  Max: 25

## Rails

RSpec/NestedGroups:
  Max: 5

## Style

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Guardfile'
    - '**/spec/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes
