# [START cloudrun_rails_cloudbuild]
steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    secretEnv: ['SECRET_KEY']
    entrypoint: 'bash'
    args: ['-c', 'docker build --no-cache --build-arg MASTER_KEY=$$SECRET_KEY --tag $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA --file Dockerfile .']

  - id: Push
    name: gcr.io/cloud-builders/docker
    args: ['push', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA']

  - id: 'DB Migrations'
    name: 'gcr.io/google-appengine/exec-wrapper'
    secretEnv: ['SECRET_KEY']
    entrypoint: 'bash'
    args: ['-c', '/buildstep/execute.sh -i $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA -s $PROJECT_ID:$_DEPLOY_REGION:$_SERVICE_NAME -e RAILS_MASTER_KEY=$$SECRET_KEY -- bundle exec rails db:migrate']

  - id: Deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/$_SECRET_NAME/versions/latest
    env: SECRET_KEY

images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: project-daedalus
  _DEPLOY_REGION: us-central1
  _LABELS: gcb-trigger-id=35398d68-d58c-4698-8f89-b81d86f61238
  _TRIGGER_ID: 35398d68-d58c-4698-8f89-b81d86f61238
  _GCR_HOSTNAME: us.gcr.io

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - project-daedalus
# [END cloudrun_rails_cloudbuild]
